Consistency: tabs to spaces

diff --git a/simple-cdd/profiles/kali.postinst b/simple-cdd/profiles/kali.postinst
--- a/simple-cdd/profiles/kali.postinst
+++ b/simple-cdd/profiles/kali.postinst
@@ -9,8 +9,8 @@
 
 configure_sources_list() {
     if grep -q '^deb ' /etc/apt/sources.list; then
-	echo "INFO: sources.list is configured, everything is fine"
-	return
+        echo "INFO: sources.list is configured, everything is fine"
+        return
     fi
 
     echo "INFO: sources.list is empty, setting up a default one for Kali"
@@ -27,27 +27,27 @@ END
 
 get_user_list() {
     for user in $(cd /home && ls); do
-	if ! getent passwd "$user" >/dev/null; then
-	    echo "WARNING: user '$user' is invalid but /home/$user exists" >&2
-	    continue
-	fi
-	echo "$user"
+        if ! getent passwd "$user" >/dev/null; then
+            echo "WARNING: user '$user' is invalid but /home/$user exists" >&2
+            continue
+        fi
+        echo "$user"
     done
     echo "root"
 }
 
 configure_zsh() {
     if grep -q 'nozsh' /proc/cmdline; then
-	echo "INFO: user opted out of zsh by default"
-	return
+        echo "INFO: user opted out of zsh by default"
+        return
     fi
     if [ ! -x /usr/bin/zsh ]; then
-	echo "INFO: /usr/bin/zsh is not available"
-	return
+        echo "INFO: /usr/bin/zsh is not available"
+        return
     fi
     for user in $(get_user_list); do
-	echo "INFO: changing default shell of user '$user' to zsh"
-	chsh --shell /usr/bin/zsh $user
+        echo "INFO: changing default shell of user '$user' to zsh"
+        chsh --shell /usr/bin/zsh $user
     done
 }
 
@@ -64,11 +64,11 @@ configure_usergroups() {
     kali_groups="adm dialout kaboxer vboxsf wireshark"
 
     for user in $(get_user_list | grep -xv root); do
-	echo "INFO: adding user '$user' to groups '$kali_groups'"
-	for grp in $kali_groups; do
-	    getent group $grp >/dev/null || continue
-	    usermod -a -G $grp $user
-	done
+        echo "INFO: adding user '$user' to groups '$kali_groups'"
+        for grp in $kali_groups; do
+            getent group $grp >/dev/null || continue
+            usermod -a -G $grp $user
+        done
     done
 }
 
@@ -78,10 +78,10 @@ pkg_installed() {
 
 configure_terminal() {
     while read -r desktop terminal; do
-	pkg_installed kali-desktop-$desktop || continue
-	echo "INFO: setting x-terminal-emulator alternative to '$terminal'"
-	update-alternatives --verbose --set x-terminal-emulator /usr/bin/$terminal || true
-	break
+        pkg_installed kali-desktop-$desktop || continue
+        echo "INFO: setting x-terminal-emulator alternative to '$terminal'"
+        update-alternatives --verbose --set x-terminal-emulator /usr/bin/$terminal || true
+        break
     done <<END
 e17   terminology
 gnome gnome-terminal.wrapper
